# Generated by Django 2.1.2 on 2018-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20181027_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglist',
            name='imgurls',
            field=models.CharField(max_length=10000),
        ),
    ]
